---

# SAML-based Authentication
# Note: this is just an example, please paremeterize the items and copy the contents to `auth.yml`

decryption-passphrase: decryption-passphrase
saml-idp-metadata: https://saml.example.com:8080
saml-bosh-idp-metadata: https://bosh-saml.example.com:8080
saml-rbac-admin-group: opsman.full_control
saml-rbac-groups-attribute: myenterprise