---

# LDAP-based Authentication
# Note: this is just an example, please paremeterize the items and copy the contents to `auth.yml`

decryption-passphrase: some-passphrase

server-url: ldap://example.com
#server-ssl-cert: 

ldap-username: cn=admin,dc=opsmanager,dc=com
ldap-password: some-password

user-search-base: ou=users,dc=opsmanager,dc=com
user-search-filter: cn={0}
group-search-base: ou=groups,dc=opsmanager,dc=com
group-search-filter: member={0}
ldap-rbac-admin-group-name: cn=opsmgradmins,ou=groups,dc=opsmanager,dc=com
email-attribute: mail
ldap-referrals: follow

#http-proxy-url: 
#https-proxy-url: 
#no-proxy: 
